### ISSUE TITLE
Automatically advance communities

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/cri#47]
It's been proposed that communities be automatically advanced through the CRI steps. Automatic advancement criteria:

Advance to Step Two
---------------------
- Client has paid for Step Two survey
- Step Two survey has been created and activated

Advance to Step Three
---------------------
- Step Two survey received responses
- Step Two survey has been deactivated
- Presentation A has concluded
- Presentation B has concluded or been opted out of
- Client has paid for Step Three survey
- Step Three survey has been created and activated

Advance to Step Four
---------------------
- Step Three survey received responses
- Step Three survey has been deactivated
- Presentation C has concluded
- Presentation D has concluded or been opted out of
- Client has paid for policy development

Notes:
------
Automatic advancement...
 - is triggered by a daily cron job
 - should be noted in activity log
 - should be accompanied by an email to the community's client(s)

Related:
- The "check it out, you got advanced" email should _also_ be sent when communities are manually advanced
- The "why isn't this community ready to be advanced" code in `AutoAdvanceShell.php` should be bundled into error messages displayed when communities are manually advanced prematurely

**Comment by bjpatterson** [comment]
This looks like an accurate representation of what I proposed.

The only potential loophole that's obvious to me is the situation where a community pays for both surveys up front, and only commits to the community presentations at a later date.  This seems a little far-fetched, but could conceivably advance a community to the next step "too soon".

Perhaps in that case, **the client should be presented with an option to expressly opt out of a presentation before they can skip over it.**  (Planning to deal with those edge cases by hand is probably also a safe option for now, though.)

**Comment by bjpatterson** [comment]
From Srikant, in an email chain, recorded here for posterity:
> The only comment I had was on the naming. Instead of step 2 survey, will it be easy to refer them as "Leadership survey".
Also, Step 3 survey = "Organizational survey"

If this change is purely internal-facing, this might not be an concern, but it also can't hurt for us to call CRI components by their public-facing names either.  It would help to standardize the way we talk about CRI.

**Comment by PhantomWatson** [comment]
> The only potential loophole that's obvious to me is the situation where a community pays for both surveys up front, and only commits to the community presentations at a later date. This seems a little far-fetched, but could conceivably advance a community to the next step "too soon".

That community could be automatically advanced to Step Three before Presentation B (Leadership Summit) if they postpone the purchasing of Presentation B until after
- The community officials questionnaire has been _closed_
- Presentation A has been _completed_
- The community organizations questionnaire has been _prepared and activated_

That seems like a pretty wide window of opportunity for making the Presentation B. Still, in that scenario, I don't imagine that there would be much in the way of negative consequences, other than potentially confusing recordkeeping.

**Comment by bjpatterson** [comment]
Issue #50 would require communities to explicitly opt-out of a presentation before moving on.  That should remove any tricky assumptions.  If a community has completed/opted out of all previous steps, then they get auto-advanced, otherwise, they stay put.

**Comment by PhantomWatson** [comment]
Issue description updated.
