### ISSUE TITLE
We need to better track OCRA billing

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#48]
## Description:
When OCRA funds a community for CRI, they aren't billed immediately. (In fact, they aren't billed until the conclusion of the Leadership Survey and related presentations, and multiple communities are billed to OCRA simultaneously to cut down on excess paperwork.)  We need a better way to manage OCRA-earmarked payments.

## Potential Tasks:
- [x] Provide a summary of OCRA-funded CRI rounds.  In particular, we need to know what communities/phases have been marked as OCRA-funded, and which are "ready to be billed.)
- [x] Distinguish between pre-billable and billable charges
- [x] Distinguish between billable and billed charges
- [x] Distinguish between billed and paid charges
- [x] DefDone: OCRA payments and related info can be tracked from a central location.

**Comment by PhantomWatson** [comment]
@bjpatterson, what's the difference between a pre-billable and billable charge to OCRA?

**Comment by PhantomWatson** [comment]
Here's the current solution: https://cri.cberdata.org/admin/purchases/ocra (accessible by clicking Payment Records in the sidebar, then the OCRA Funding button at the top).

Right now it's just a simple list of all OCRA-associated payments and a sum of all costs at the top.

**Comment by bjpatterson** [comment]
@PhantomWatson: I believe the intent behind pre-billable designation was that we don't want to bill OCRA for work yet to be completed. By that definition:
- **Pre-Billable**: any OCRA payment linked to a community that hasn't finished the related presentation
- **Billable**: any OCRA payment linked to a community that *has* received the related presentation, but has not yet been refunded by OCRA.

**Comment by bjpatterson** [comment]
I also think that page is exactly what ICI is looking for, just something that shows what work we've done that hasn't been paid for yet.

Once we get the pre-billable, billable, paid categories sorted out, I suggest we also group items on that page similarly, so that we have an at-a glance summary of any outstanding charges .

**Comment by PhantomWatson** [comment]
Here's my understanding of our "billable" criteria:
- Community Leadership Alignment Assessment
  - The date of the community's Step Two mandatory presentation has passed
- Leadership Summit
  - The date of the community's Step Two optional presentation has passed
- Community Organizations Alignment Assessment
  - The date of the community's Step Three mandatory presentation has passed
- Facilitated Community Awareness Conversation
  - The date of the community's Step Three optional presentation has passed
- PWRRR Policy Development
  - **For the moment:** Community has been advanced to Step Four
  - **Replace with:** CBER / ICI confirms delivery of policy development (via a button on the CRI site)

**Comment by bjpatterson** [comment]
Seems correct.

It might be worth noting that as of right now, OCRA only vouches for the first two presentations, and when a community is paying directly, we collect the money up front.  So unless OCRA starts funding additional phases, we effectively don't need a "billable" policy for those later stages. It doesn't hurt to have one, but I wanted to make it clear that the policy only applies to OCRA (and possibly other sources of non-community funding).

(We might eventually want some logic behind which payments are allowed to be earmarked for OCRA, but that's a separate issue I think.)

**Comment by PhantomWatson** [comment]
Good points all around. I had forgotten that OCRA was only funding all the Step Two stuff.

Payment record validation has been updated and new records can no longer be added that claim OCRA funding for anything but the Step Two products.
