### ISSUE TITLE
Provide an explicit "opt-out" option when scheduling a presentation

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#50]
## Description:
Creating an explicit opt-out option would allow simplified tracking logic in the to-do list (since we won't have to assume a community's disposition).  If a community opts out of presentation B, we know to start a discussion about paying for presentation C.  If they opt out of B, C, and D (and probably the policy development as well), we can remove them from the to-do list altogether.

## Potential tasks:
- [x] Add "opt-out" options to the presentation scheduling page
- [x] Add "opt-out" options to the Client Home page
- [x] Work the new option into the logic behind the To-Do page
- [x] Surface the opt-out option in any applicable reports
- [x] Add "You have opted out of any further participation in CRI. If you'd like to resume..." message in Client Home if appropriate
- [x] defDone: We have a robust method for tracking a community's decision to skip certain phases of CRI

**Comment by PhantomWatson** [comment]
Added "Add 'opt-out' options to the Client Home page".

**Comment by PhantomWatson** [comment]
The way I'm thinking of organizing this is to present the client with an "opt out" alternative wherever there's a prompt to pay for something (survey + mandatory presentation, optional presentation, or policy development). Internally, the site will keep records of "purchase opt-outs" similarly to (but more simply than) how it tracks purchases.

So on the Client Home page, wherever there's a **[Purchase]** button, there will be an **[Opt Out]** button. After clicking on it, this section will display a "You have opted out" message, and we might add in an "I changed my mind, please take all my money" link later on.

On the Community Presentations page for admins, there will be a  **[Community opts out]** option for each presentation in case we want to record those opt-outs ourselves.

**Comment by bjpatterson** [comment]
I like this approach.

If we aren't going to implement the "I changed my mind, take my money" option now, I suggest that the opt-out button have a few "are you really sure you want to do this?" hoops to prevent clients from accidentally locking themselves out of the payments area.
