### ISSUE TITLE
~Monthly Status Reporting

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#52]
## Description:
A ~monthly status report for OCRA has been suggested as a way to keep them reasonably satisfied.  This should be a short executive report that is quick to consume.  Potentially just a few columns, such as the name of each community, their current status within CRI, and the date of last activity.  This should be a downloadable excel report near the more detailed OCRA report.

## Potential Tasks
- [x] define status snippets
- [x] implement report
- [x] defDone: we can easily send OCRA an executive snapshot of CRI every few weeks to keep them happy

**Comment by PhantomWatson** [comment]
That should be pretty easy. There's already a simple "status" column that summarizes what's currently going on with a community and could be elaborated upon. This should just require a new, simpler auto-generated spreadsheet that can be downloaded like the current ones.

With this proposal, we'd have four versions of what we're calling "reports". I suggest we start referring to them like this:
- **Web-based admin report** (the HTML table for admins, with toggleable columns)
- **Admin report spreadsheet**
- **OCRA full report spreadsheet** (currently available)
- **OCRA summary report spreadsheet** (what's being proposed now)
