### ISSUE TITLE
Make "Report Deliverables" page

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/cri#59]
In order to track some things that aren't currently being tracked by the site, we'll need some sort of "report deliverables" page. I suggest this:

Report Deliverables
--------------------
- Report delivery of policy development to the client
- Report delivery of presentation materials to ICI

This would record:
- the item delivered
- the time reported
- the administrator who reported it
- and the community, if relevant

These records would be reflected in the transition from "waiting for CRI staff to..." messages into "ready to move on to next step" messages in:
- the Client Home page
- Admin To-Do page

This will allow us to wrap up issues:
- #53: Marking communities as "done"
- #51: Admin To-Do list

**Comment by bjpatterson** [comment]
I think the billing portion might need a dedicated page, but reporting for the policy development and presentation materials could likely be incorporated directly into the to-do list (or at minimum linked to from there).

I'm OK with having a dedicated page for money matters, but I'm wary about adding too many special pages for specific day to day tasks. We want to keep the to-do page as "universal" as possible, in my opinion.

**Comment by PhantomWatson** [comment]
Yeah, that's been my biggest apprehension too. I don't want to overload the sidebar with a dozen links and make the whole site unwieldy.

These are good ideas. OCRA billing stuff could be reported from the [OCRA Funding](https://cri.cberdata.org/admin/purchases/ocra) page and presentation / policy delivery could be reported from the To-Do page.
